//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Frame.msg.
//

#ifndef __FRAME_M_H
#define __FRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Frame;
/**
 * Class generated from <tt>Frame.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Frame
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int header;    // the data sequence number.
 *     string payload; //the message contents after byte stuffing (in characters).
 *     char trailer; //CRC
 *     int frameType; // Data=2 / ACK=1 /NACK=0.
 *     int ack_nack_number;
 * }
 * </pre>
 *
 * Frame_Base is only useful if it gets subclassed, and Frame is derived from it.
 * The minimum code to be written for Frame is the following:
 *
 * <pre>
 * class Frame : public Frame_Base
 * {
 *   private:
 *     void copy(const Frame& other) { ... }

 *   public:
 *     Frame(const char *name=nullptr, short kind=0) : Frame_Base(name,kind) {}
 *     Frame(const Frame& other) : Frame_Base(other) {copy(other);}
 *     Frame& operator=(const Frame& other) {if (this==&other) return *this; Frame_Base::operator=(other); copy(other); return *this;}
 *     virtual Frame *dup() const override {return new Frame(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from Frame_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(Frame)
 * </pre>
 */
class Frame_Base : public ::omnetpp::cPacket
{
  protected:
    int header = 0;
    omnetpp::opp_string payload;
    char trailer = 0;
    int frameType = 0;
    int ack_nack_number = 0;

  private:
    void copy(const Frame_Base& other);

  protected:
    bool operator==(const Frame_Base&) = delete;
    // make constructors protected to avoid instantiation
    // make assignment operator protected to force the user override it
    Frame_Base& operator=(const Frame_Base& other);

  public:
    Frame_Base(const char *name=nullptr, short kind=0);
    Frame_Base(const Frame_Base& other);
    virtual ~Frame_Base();
    virtual Frame_Base *dup() const override
    {return new Frame_Base(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHeader() const;
    virtual void setHeader(int header);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual char getTrailer() const;
    virtual void setTrailer(char trailer);

    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);

    virtual int getAck_nack_number() const;
    virtual void setAck_nack_number(int ack_nack_number);
};


namespace omnetpp {

template<> inline Frame_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<Frame_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FRAME_M_H

